spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/unitedgo_user
    username: root
    password: ken
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    discovery:
      enabled: true
    consul:
      host: localhost
      discovery:
        hostname: localhost
server:
  port: 8006
resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s